---
title: "Leaflet Investigation App"
author: "Rohan Danis-Cox"
date: "6/10/2019"
output:
  html_document: default
---
<br>
This application allows users to view a map of NSW with each measure visualised in colour. To assist with managing memory, measures have been grouped into categories which can be selected using the drop down on the next tab. While this app runs perfectly well locally, to host the app on shinyapps.io I have had to simplify the polygons used for each suburb significantly. I hope this doesn't detract from the experience. Additionally, the load times on shinyapps.io are much slower,<b> so please be patient as it can take up to 1 minute each time the drop down is used.</b>

Full code can be found here: <https://github.com/RohanDanisCox/ilab_2019/>

My blog describing my progress throught iLab 2019 and building these apps is available here: <https://16-3327.ca.uts.edu.au/ilab-1-2019/>

This application is one of three I have built for my iLab 2019 project. The other two are:

* A suburb investigation app which allows users to look closely at up to three suburbs and inspect variables. Find it here: <https://rohandaniscox.shinyapps.io/suburb_investigation_app/>
* A suburb comparison app which allows users to investigate which suburbs in 2019 are similar in characteristics to other suburbs in past years. Find it here: <https://rohandaniscox.shinyapps.io/similarity_app/>

This application makes use of the Leaflet mapping package and combines data from the following sources: