---
title: "Suburb Investigator App"
author: "Rohan Danis-Cox"
date: "6/10/2019"
output: html_document
---
<br>
This application allows users to navigate through suburbs in NSW and investigate qualities measured on each suburb. 

Suburbs should be selected by using the drop downs on the left, starting from the top. 

The display includes: 

* A map of the Statistical Area 4 (SA4), with the Statistical Area 3 (SA3) highlighted in pink and the chosen suburb highlighted in red.

* A line graph showing the change over time in the selected variable

* A density graph showing the full distribution for the selected variable across NSW. The red vertical lines indicate years of the selected suburb within that distribution.

Full code can be found here: <https://github.com/RohanDanisCox/ilab_2019/>

My blog describing the activities take is availabel here: <https://16-3327.ca.uts.edu.au/ilab-1-2019/>

This application is one of three I have built for my iLab 2019 project. The other two are:

* A map-based variable investigation app using Leaflet, which allows users to visualise groupings of variables across all of NSW. Find it here: <https://rohandaniscox.shinyapps.io/leaflet_investigation_app/>
* A suburb comparison app which allows users to investigate suburbs in 2019 which are similar to either a set of inputs or another suburb. Find it here: <https://rohandaniscox.shinyapps.io/similarity_app/>

This application makes use of the Leaflet mapping package and combines data from the following sources:

